import React from 'react';
import { Breadcrumbs } from '../components/common/Breadcrumbs';
import { SeoHead } from '../components/common/SeoHead';
import { ShieldCheck, Mail, FileText, Lock, AlertTriangle, Copyright } from 'lucide-react';

interface LegalPageProps {
  type: 'about' | 'contact' | 'privacy-policy' | 'terms' | 'disclaimer' | 'dmca' | 'cookie-policy';
}

export const LegalPage: React.FC<LegalPageProps> = ({ type }) => {
  const getLegalTitle = () => {
    switch (type) {
      case 'about':
        return 'About OmniTools';
      case 'contact':
        return 'Contact Us';
      case 'privacy-policy':
        return 'Privacy Policy';
      case 'terms':
        return 'Terms of Use';
      case 'disclaimer':
        return 'Disclaimer';
      case 'dmca':
        return 'DMCA Policy';
      case 'cookie-policy':
        return 'Cookie Policy';
    }
  };

  const title = getLegalTitle();

  return (
    <>
      <SeoHead title={`${title} | OmniTools`} description={`Read the official ${title} for OmniTools.`} />

      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-6 space-y-8">
        <Breadcrumbs items={[{ label: title }]} />

        <div className="space-y-4">
          <h1 className="text-3xl sm:text-4xl font-black text-slate-900 dark:text-white tracking-tight">
            {title}
          </h1>
          <p className="text-xs text-slate-400">Last updated: January 2026</p>
        </div>

        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-6 sm:p-8 space-y-6 text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
          {type === 'about' && (
            <div className="space-y-4">
              <p>
                <strong>OmniTools</strong> is a free, fast, and privacy-first suite of over 200+ web utilities created for developers, designers, writers, and marketers.
              </p>
              <h3 className="font-bold text-base text-slate-900 dark:text-white">Our Core Mission</h3>
              <p>
                We believe that web utilities should be lightning-fast, ad-friendly, and 100% private. Unlike legacy tools that upload your sensitive images, JSON data, or credentials to remote servers, OmniTools executes all logic directly in your browser using modern Web APIs.
              </p>
            </div>
          )}

          {type === 'contact' && (
            <div className="space-y-4">
              <p>Have questions, feature requests, or business inquiries? Get in touch with our engineering team.</p>
              <div className="p-4 bg-slate-50 dark:bg-slate-800 rounded-2xl space-y-2">
                <p className="font-bold text-slate-900 dark:text-white">Email Inquiries:</p>
                <a href="mailto:support@omnitools.app" className="text-indigo-600 dark:text-indigo-400 font-mono font-semibold">
                  support@omnitools.app
                </a>
              </div>
            </div>
          )}

          {type === 'privacy-policy' && (
            <div className="space-y-4">
              <h3 className="font-bold text-base text-slate-900 dark:text-white">1. Client-Side Data Security</h3>
              <p>
                OmniTools operates under a strict client-side architecture. All image compression, JSON formatting, hash calculations, and text transformations are performed locally within your browser's JavaScript environment. We do not transmit or store your files on external servers.
              </p>
              <h3 className="font-bold text-base text-slate-900 dark:text-white">2. Analytics & Cookies</h3>
              <p>
                We use standard, anonymized browser local storage (`localStorage`) to remember your dark/light theme preference and favorite tools.
              </p>
            </div>
          )}

          {type === 'terms' && (
            <div className="space-y-4">
              <p>By accessing or using OmniTools, you agree to be bound by these Terms of Use.</p>
              <p>All tools are provided "as is" without warranty of any kind, express or implied.</p>
            </div>
          )}

          {type === 'disclaimer' && (
            <div className="space-y-4">
              <p>
                The outputs generated by our calculators, converters, and cryptographic generators are intended for general utility purposes. Users should verify critical calculations independently.
              </p>
            </div>
          )}

          {type === 'dmca' && (
            <div className="space-y-4">
              <p>OmniTools respects intellectual property rights. If you believe your copyrighted work is used improperly, email support@omnitools.app.</p>
            </div>
          )}

          {type === 'cookie-policy' && (
            <div className="space-y-4">
              <p>We use essential local storage keys (`omnitools_theme`, `omnitools_history`) to store user interface preferences.</p>
            </div>
          )}
        </div>
      </div>
    </>
  );
};
